version: "3.9"
services:
  broker:
    build:
      context: .
    environment:
      CONFIG_FILE_PATH: "/tmp/hermes/config.json"
    volumes:
      - hermes_volume:/tmp/hermes
    ports:
      - 4000:4000
      - 5000:5000
volumes:
  hermes_volume:
    external: true
