name: Docker

on:
  push:
    branches:
      - master

jobs:
  build_image:
    name: Build Image
    runs-on: ubuntu-20.04

    steps:
      - name: Check out code
        uses: actions/checkout@v2.3.4

      - name: Setup buildx
        uses: docker/setup-buildx-action@v1.3.0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1.9.0
        with:
          registry: ghcr.io
          username: $GITHUB_ACTOR
          password: ${{ secrets.CR_PAT }}

      - name: Build and push
        uses: docker/build-push-action@v3.1.0
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          username: $GITHUB_ACTOR
          password: ${{ secrets.CR_PAT }}
          push: true
          tags: |
            ghcr.io/c16a/hermes/hermes:latest
