name: Docker

on:
  push:
    branches:
      - master
  pull_request:
    branches: [ master ]

jobs:
  build_image:
    name: Build Image
    runs-on: ubuntu-20.04

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/c16a/hermes/hermes:latest
