name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-20.04 ]

    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Run tests
        run: go test -v ./...

  build:
    name: Build
    runs-on: ${{ matrix.os }}
    needs:
      - test
    strategy:
      matrix:
        os: [ ubuntu-20.04 ]
    steps:

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get dependencies
        run: |
          go mod tidy

      - name: Build Linux x64
        run: GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o build/hermes_linux_amd64 github.com/c16a/hermes/app

      - name: Store Linux x64 artifacts
        uses: actions/upload-artifact@v2
        with:
          name: hermes_linux_amd64
          path: build/hermes_linux_amd64

      - name: Build Linux ARM 64-bit
        run: GOOS=linux GOARCH=arm64 go build -ldflags="-s -w" -o build/hermes_linux_arm64 github.com/c16a/hermes/app

      - name: Store Linux ARM 64-bit artifacts
        uses: actions/upload-artifact@v2
        with:
          name: hermes_linux_arm64
          path: build/hermes_linux_arm64

      - name: Build Linux OpenPOWER 64-bit
        run: GOOS=linux GOARCH=ppc64le go build -ldflags="-s -w" -o build/hermes_linux_ppc64le github.com/c16a/hermes/app

      - name: Store Linux OpenPOWER 64-bit artifacts
        uses: actions/upload-artifact@v2
        with:
          name: hermes_linux_ppc64le
          path: build/hermes_linux_ppc64le

      - name: Build Windows x64
        run: GOOS=windows GOARCH=amd64 go build -ldflags="-s -w" -o build/hermes_windows_amd64.exe github.com/c16a/hermes/app

      - name: Store Windows x64 artifacts
        uses: actions/upload-artifact@v2
        with:
          name: hermes_windows_amd64.exe
          path: build/hermes_windows_amd64.exe

      - name: Build macOS Intel x64
        run: GOOS=darwin GOARCH=amd64 go build -ldflags="-s -w" -o build/hermes_mac_amd64 github.com/c16a/hermes/app

      - name: Store macOS Intel x64 artifacts
        uses: actions/upload-artifact@v2
        with:
          name: hermes_mac_amd64
          path: build/hermes_mac_amd64


